In [4]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [24]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [25]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [26]:
#dividing into dependent and independent featured

In [27]:
x = dataset.iloc[:,3:13]
y = dataset.iloc[:,13]

In [28]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [29]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [30]:
# feature engineering
geography  = pd.get_dummies(x['Geography'],drop_first=True)
gender = pd.get_dummies(x['Gender'],drop_first=True)

In [31]:
geography

Germany  Spain
0       False  False
1       False   True
2       False  False
3       False  False
4       False   True
...       ...    ...
9995    False  False
9996    False  False
9997    False  False
9998     True  False
9999    False  False

[10000 rows x 2 columns]

In [32]:
# add this with df
x=x.drop(['Geography','Gender'],axis = 1)

In [33]:
pd.concat([x,geography,gender],axis=1)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain   Male  
0                  1        101348.88    False  False  False  
1                  1        112542.58    False   True  False  
2                  0        113931.57    False  False  False  
3                  0         93826.63    False  False  False  
4                  1         79084.10    False   True  False  
...              ...              ...      ...    ...    ...  
9995               0         96270.64    False  False   True  
9996               1        101699.77    False  False   True  
9997               1         42085.58    False  False  False  
9998               0         92888.52     True  False   True  
9999               0         38190.78    False  False  False  

[10000 rows x 11 columns]

In [34]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [35]:
# feature scaling is required for - Ann,linear reg,logistic reg, kknn,k means
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [36]:
x_train

array([[ 0.16958176, -0.46460796,  0.00666099, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945,  0.30102557, -1.37744033, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591, -0.94312892, -1.031415  , ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521, -0.08179119,  1.39076231, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079,  0.87525072, -1.37744033, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [37]:
x_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-1.31490297,  0.10961719, -1.031415  , ...,  0.64259497,
        -1.03227043,  0.49587037],
       [ 0.57162971,  0.30102557,  1.04473698, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-0.00566991, -0.46460796, -0.33936434, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-0.79945688, -0.84742473,  1.04473698, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [39]:
# creating ann
# using tensorflow

In [41]:
from tensorflow.keras.models import Sequential # for  forward and bakward propagation
from tensorflow.keras.layers import Dense # used to create input,hidden,op layer
from tensorflow.keras.layers import LeakyReLU,PReLU,ELU,ReLU # activation function
from tensorflow.keras.layers import Dropout  # for dead nodes

In [42]:
classifier = Sequential()

In [43]:
# input layer
classifier.add(Dense(units=11,activation='relu')) # inputs = 11

In [44]:
# first hidden layer
classifier.add(Dense(units=7,activation='relu'))

In [45]:
#second hidden layer
classifier.add(Dense(units=6,activation='relu'))

In [46]:
# adding op layer
classifier.add(Dense(units=1,activation='sigmoid')) # for binary = signmoid

In [47]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [48]:
model_history = classifier.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.7434 - loss: 0.5543 - val_accuracy: 0.8058 - val_loss: 0.4537
Epoch 2/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8203 - loss: 0.4391 - val_accuracy: 0.8175 - val_loss: 0.4330
Epoch 3/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8219 - loss: 0.4192 - val_accuracy: 0.8190 - val_loss: 0.4246
Epoch 4/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8296 - loss: 0.4103 - val_accuracy: 0.8258 - val_loss: 0.4149
Epoch 5/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8363 - loss: 0.4079 - val_accuracy: 0.8330 - val_loss: 0.4056
Epoch 6/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8333 - loss: 0.4000 - val_accuracy: 0.8364 - val_loss: 0.3997
Epoch 7/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8456 - loss: 0.3822 - val_accuracy: 0.8395 - val_loss: 0.3887
Epoch 8/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8503 - loss: 0.3653 - val_accu

In [49]:
# here we have to perfirn early stopping
# early stopping is when accuracy is not increasing in epochs

In [50]:
import tensorflow as tf
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor = "val_loss",
    min_delta = 0.0001,
    patience = 20,
    verbose = 1,
    mode = "auto",
    baseline = None,
    restore_best_weights = False,
)

In [51]:
# use below instead  of above train code code
# model_history = classifier.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=100,,callbacks = early_stopping)

In [52]:
model_history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [53]:
# prediction
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step


In [54]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[1536,   59],
       [ 218,  187]])

In [55]:
from sklearn  import metrics
score = metrics.accuracy_score(y_test,y_pred)
score

0.8615

In [57]:
# checking the weights
classifier.get_weights()

[array([[-6.43830150e-02, -9.48477886e-04, -5.55469573e-01,
         -4.49146450e-01,  9.98974871e-03, -1.64561212e-01,
          4.48909551e-01,  2.45310534e-02,  9.13174003e-02,
         -5.87977469e-03,  1.74110159e-01],
        [-7.30956554e-01, -4.42224830e-01, -1.16355635e-01,
         -5.18490493e-01, -7.74972215e-02, -3.08537900e-01,
         -9.22542155e-01,  3.87039393e-01,  1.22507095e-01,
         -8.47186804e-01, -6.95903003e-01],
        [-1.28577784e-01,  2.11653709e-01,  4.90736008e-01,
          4.57712144e-01, -1.41751379e-01, -9.89052773e-01,
         -3.00326169e-01, -7.04036057e-02, -1.43546686e-01,
          7.68730938e-02, -2.72094816e-01],
        [-2.27380637e-02, -1.04738331e+00,  1.78328872e-01,
          6.57183647e-01, -1.84998184e-01,  1.77800998e-01,
          4.27567899e-01, -1.79870993e-01,  2.19118208e-01,
         -4.24521536e-01,  3.47189248e-01],
        [-1.19869567e-01, -2.68277526e-01,  2.84459054e-01,
         -2.09203437e-02, -1.25517178e+00, -